ez_hybrid_platform_ui_dashboard:
    path: /dashboard
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Dashboard:viewDashboard
    methods: [GET]

ez_hybrid_platform_ui_location_update_sub_items_order:
    path: /location/update/{locationId}/{contentId}
    defaults:
        _controller: EzSystemsHybridPlatformUiBundle:Location:updateSubItemOrder
    methods: [POST]
